### ISSUE TITLE
When cancel, it doesn't return the stock.

### ISSUE THREAD

**Issue by cuiyang000** [bambora/payform-magento-v2.x#1]
Since v2.3 there's this inventory_reservation table records the reservations of the stock related to orders.

When placing order with Bambora it adds a record with quantity -1 (or more depends on how many in the cart) to reserve the quantity, however when cancel, it doesn't add another record with quantity=1 to cancel the reservation. Which has caused some quantities been reserved forever, and the products which has qty in stock in reality but cannot be purchased in webshop.

If I change the cancellation code in app/code/Bambora/PayForm/Controller/Checkout/CheckReturn.php to:
`$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			$orderManagement = $objectManager->get('Magento\Sales\Api\OrderManagementInterface');
			$orderManagement->cancel($order->getId());
			$order->addStatusHistoryComment($comment)->save();`

Then it works fine, so please look into this issue.

**Comment by henrisuvanto** [comment]
Thank you for reporting the issue. The issue has now been fixed in the 1.4.0 version of the module.
